dataset: imagenet
root_dir: ./

image_res: 256
second_input_size: 128
vision_width: 1024
embed_dim: 256
temp: 0.07
batch_size_train: 512
batch_size_test: 512

alpha: 0.4
num_answers: 3129
context_max_length: 25
max_length: 25
num_beams: 1
temperature: 1
top_k: 0
top_p: 1
repetition_penalty: 1
length_penalty: 1
early_stopping: false
num_return_sequences: 1
eos: '[SEP]'
loss_type: 'kl' # bce or kl

bert_config: 'configs/config_bert.json'
init_encoder: False
init_decoder: False

# dalle
discrete_vae_weight_path: "./vqgan_ckpt"
discrete_vae_type: "vqgan"

lr: 5e-4
epochs: 100
optimizer: "adamw"